#!/usr/bin/env zsh

FONT_FACE="Hack Nerd Font"

PLUGIN_DIR="$CONFIG_DIR/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

source "$CONFIG_DIR/colors.sh"

sketchybar --bar \
             height=32 \
             y_offset=4 \
             color=0x00000000 \
             margin=1 \
             sticky=on \
             padding_left=8 \
             padding_right=8 \
             notch_width=188 \
             font_smoothing=true


sketchybar --default \
             background.color=$BASE \
             background.corner_radius=5 \
             background.padding_right=5 \
             background.height=28 \
             icon.font="$FONT_FACE:Regular:15.0" \
             icon.padding_left=7 \
             icon.padding_right=5 \
             label.font="$FONT_FACE:Regular:12.0" \
             label.color=$TEXT \
             label.y_offset=0 \
             label.padding_left=0 \
             label.padding_right=7

# sketchybar --add event spotify_change $SPOTIFY_EVENT \
#            --add item spotify e \
#            --set spotify \
#                  icon= \
#                  label.drawing=off \
#                  label.padding_left=3 \
#                  script="$PLUGIN_DIR/spotify.sh" \
#            --subscribe spotify spotify_change mouse.clicked

sketchybar --add item current_space left \
           --set current_space \
                 background.color=$BLUE \
                 background.height=26 \
                 icon.font="$FONT_FACE:Regular:12.0" \
                 icon.color=$BASE \
                 label.drawing=off \
                 script="$PLUGIN_DIR/current_space.sh" \
           --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
           --set front_app \
                 background.color=$GREEN \
                 background.height=28 \
                 background.padding_left=0 \
                 background.padding_right=0 \
                 icon.font="sketchybar-app-font:Regular:15.0" \
                 icon.color=$BASE \
                 label.drawing=no \
                 script="$PLUGIN_DIR/front_app.sh" \
           --add item front_app.name left \
           --set front_app.name \
                 background.color=$BASE \
                 background.padding_left=7 \
                 icon.drawing=off \
                 label.font="$FONT_FACE:Regular:12.0" \
                 label.color=$TEXT

sketchybar --add bracket front_app_bracket \
                         front_app \
                         front_app.name \
           --subscribe front_app front_app_switched

# sketchybar --add item weather q \
#            --set weather \
#                  background.padding_right=0 \
#                  icon.color=$PINK\
#                  icon.font="$FONT_FACE:Regular:15.0" \
#                  update_freq=1800 \
#                  script="$PLUGIN_DIR/weather.sh" \
#            --subscribe weather system_woke

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
           --set clock \
                 icon=󰃰 \
                 icon.color=$ROSEWATER \
                 update_freq=5 \
                 script="$PLUGIN_DIR/clock.sh"

sketchybar --add item battery right \
           --set battery \
                 update_freq=20 \
                 script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
           --set volume \
                 icon.color=$SKY \
                 label.drawing=true \
                 script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change

sketchybar --add item keyboard right        \
           --set keyboard \
                 icon=󰌌 \
                 icon.color=$LAVENDER \
                 script="$PLUGIN_DIR/keyboard.sh" \
           --add event keyboard_change "AppleSelectedInputSourcesChangedNotification" \
           --subscribe keyboard keyboard_change

# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
