[manager]
prepend_keymap = [
    { on = ["g", "d" ], run = "cd ~/Downloads/", desc = "Downloads" },
    { on = ["g", "c" ], run = "cd ~/.config/", desc = "Config" },
    { on = ["g", "r" ], run = "cd ~/Repos/", desc = "Repos" },
    { on = ["g", "m" ], run = "cd ~/Masters/", desc = "Masters"},
    { on = ["g", "i" ], run = "cd ~/Library/Mobile\\ Documents/com~apple~CloudDocs/", desc = "iCloud"},
    { on = [ "z", "u" ], run = "shell --confirm 'unzip $@'", desc = "Unzip file" },
    { on = ["z", "c"], run = "plugin compress", desc = "Zip files"},
]
